### ISSUE TITLE
Semantics of `set_buffer` are not documented

### ISSUE THREAD

**Issue by LoganDark** [john01dav/softbuffer#16]
It takes a slice. Is this slice immediately cloned, or does the window keep a reference to it? Should I double-buffer, or can I clobber the buffer after the call to `set_buffer`?

Normally the fact that the slice doesn't stay borrowed would be a hint, but as this is a relatively new library using unsafe code, it's possible that it could be accidentally unsound, which is why documenting this would be helpful.

**Comment by LoganDark** [comment]
It looks like the types are indeed correct and `set_buffer` copies.

**Comment by i509VCB** [comment]
It might be useful to provide a `&mut u8` or something of that nature you could write into.

Although I don't know how each platform works regarding that.

**Comment by LoganDark** [comment]
> It might be useful to provide a `&mut u8` or something of that nature you could write into.
> 
> Although I don't know how each platform works regarding that.

AFAIK this is generally the case with GPU crates because they typically have weird and difficult-to-satisfy requirements regarding memory alignment, stride and etc. However, software buffers don't usually have this limitation.

**Comment by john01dav** [comment]
As the semantics are indeed what the signature says, I am closing this issue. If you need some of the other things discussed here (e.g. a `&mut u8`, or, more likely, a `&mut u32`), then feel free to create a new issue :).
